### ISSUE TITLE
Add unit description to input fields

### ISSUE THREAD

**Issue by PChild** [team401/MP-Generator#4]
I know units are called out in the readme, but I think we should also have units included in the field labels so that people don't get confused when using it. Just having `Width: 2` is much less clear than `Robot Width (ft): 2`

**Comment by DarkenedDragon** [comment]
I've had it like that so the text fields don't crowd the path buttons. You'll also notice that, when empty, the width text field already says "Robot width (feet)."

**Comment by PChild** [comment]
Good enough for me!
